FROM nvcr.io/nvidia/deepstream:5.1-21.02-base 


WORKDIR /root

RUN apt-get update
RUN apt-get -y install python3-pip
RUN pip3 install numpy
RUN pip3 install image
RUN pip3 install torchvision==0.9.1
RUN pip3 install torch==1.8.1
RUN pip3 install pycocotools



COPY . .

CMD python3 server2.py 
