Create a directory enter it and create your file [touch/nano/vim Dockerfile] . 

##### simple example of a Dockerfile ####

FROM ubuntu:latest
MAINTAINER Guy Azulay "guykort98@gmail.com"

RUN apt-get update -y && apt-get upgrade -y 
RUN apt-get install python3-pip -y 
RUN pip3 install Flask -y
RUN pip3 install boto3 && apt-get install awscli 
RUN apt-get install curl -y && apt-get install net-tools -y
RUN echo "Finished"

COPY net4u_forever.sh /usr/local/bin/net4u_forever.sh ### copy the script
RUN chmod +x /usr/local/bin/net4u_forever.sh







######### Finaly to build the image : 

    > sudo docker build -t [Your dockerfile] .
    
 After you create ubuntu image and create a container you can log in at the following point:
[ docker run -it ubuntu ] 
or : 
[ docker run -t -i ubuntu /bin/bash ]

afetr that you need to do [ apt-get update ] and then you can install packages in your ubuntu.


